services:
  index:
    image: ghcr.io/sourmash-bio/branchwater:index-0.3.0
    build:
      context: .
      dockerfile: Dockerfile
      target: index
    restart: always
    volumes:
      - ./bw_db:/data/
    env_file:
      - prod.index.env

  app:
    image: ghcr.io/sourmash-bio/branchwater:web-0.3.0
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - index
    volumes:
      - ./bw_db:/data/
    env_file:
      - prod.env
    command: >
      gunicorn
        --bind 0.0.0.0:8000
        --timeout 120
        --workers 4
        --access-logfile -
        main:app
