FROM ghcr.io/prefix-dev/pixi:0.16.0 AS build
COPY . /tmp/build

WORKDIR /tmp/build

RUN apt-get update && apt-get -y install ca-certificates
RUN pixi run -e build build-server

# Final image is based on scratch. We only copy the server binary,
# no need for pixi anymore
FROM scratch

COPY --from=build /tmp/build/target/release/branchwater-server /app/bin/

WORKDIR /data

EXPOSE 80/tcp

CMD ["/app/bin/branchwater-server", "--port", "80", "-k21", "--location", "/data/sigs.zip", "/data/index"]
