name: "Test"
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'crates/**'
      - Cargo.toml
      - Cargo.lock
      - flake.nix
      - flake.lock
  push:
    branches:
      - 'main'

jobs:
  tests:
    strategy:
      # Allow other jobs to finish building and cache properly before bailing
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v16
    - name: flake checks
      run: nix flake check --keep-going --print-build-logs

